name: Publish Frontend Docker Image
run-name: Publishing Frontend Docker Image...
on:
  push:
    branches: main

jobs:
  push_to_registry:
    name: Push Frontend Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Frontend
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: evandvance/bekindlytodayfrontend

      - name: Build and push Frontend Docker Production Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: prod
          tags: evandvance/bekindlytodayfrontend:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Frontend Docker Dev Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: dev
          tags: evandvance/bekindlytodayfrontend:dev
          labels: ${{ steps.meta.outputs.labels }}

      - name: Redeploy on Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
